services:
  web:
    image: ghcr.io/sarslanian/tinytron-web:latest
    environment:
      EXPRESS_URL: http://server:3000
    ports:
      - "3001:3001"
    restart: unless-stopped
    depends_on:
      - server

  server:
    image: ghcr.io/sarslanian/tinytron-server:latest
    environment:
      NODE_ENV: production
      CTA_API_KEY: ${CTA_API_KEY}
      MQTT_USERNAME: ${MQTT_USERNAME}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      mosquitto:
        condition: service_healthy

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    environment:
      MQTT_USERNAME: ${MQTT_USERNAME}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
    entrypoint: >
      sh -c "
        mosquitto_passwd -c -b /mosquitto/config/passwd \"$$MQTT_USERNAME\" \"$$MQTT_PASSWORD\" &&
        chmod 0700 /mosquitto/config/passwd &&
        exec /docker-entrypoint.sh mosquitto -c /mosquitto/config/mosquitto.conf
      "
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_sub -t '$$SYS/#' -C 1 -i healthcheck -W 3 -u $${MQTT_USERNAME} -P $${MQTT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  mosquitto_data:
